config/routes.rb
CalculadoraInfonavit::Application.routes.draw do
  resources :pages, path: "calcula-tu-credito" do
    get "vsm", on: :collection
    post "calcular_vsm", on: :collection
    get "pesos", on: :collection
  end

  root 'pages#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def vsm
  end

  def pesos
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def callback
    auth # Do what you want with the auth hash!
  end

  def auth; request.env['omniauth.auth'] end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Calculadora de Credito Infonavit</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Calculadora de Credito Infonavit", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Inicio", root_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Calcula tu credito <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "En VSM", vsm_pages_path %></li>
              <li><%= link_to "En Pesos", pesos_pages_path %></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div id="body" class="container">
    <div class="row-fluid">
      <div class="col-xs-12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/pages/index.html.slim
div class="jumbotron"
  h1 Calcula tu Credito Ahora Mismo!
  p ¿Quieres saber cuanto $$DINERO$$ estaras pagando durante la vida util de tu credito Infonavit?. No esperes mas y mira como se comporta si haces contribuciones voluntarias
  p
    = link_to "Calcula tu Credito Infonavit Ahora", "", class: "btn btn-primary btn-lg"
div class="panel panel-default"
  div class="panel-heading"
    h3 class="panel-title" Acerca de nosotros
  div class="panel-body"
    p Este sitio web fue desarrollado por un grupo de desarrolladores web de Monterrey, N.L. con la finalidad de poder calcular de manera mas clara como sería el comportamiento de un <strong>Credito Infonavit</strong> en cualquiera que fuera su modalidad.
    P Hacemos enfasis en lo siguiente: <strong>NO TENEMOS NINGUNA RELACIÓN CON INFONAVIT NI CON SUS PROCESOS, UNICAMENTE REPLICAMOS LOS ESQUEMAS DE PAGO EN BASE A SITUACIONES CREDITICIAS ESPECIFICADAS POR EL USUARIO FINAL.</strong>
    p Nosotros no calculamos tus puntos o el saldo que Infonavit te ofrece, solo calculamos el comportamiento de tus futuros pagos en base a ciertos criterios como, aportaciones patronales, aportaciones voluntarias, etc.

app/views/pages/pesos.html.slim
div class="jumbotron"
  h1 Calcula tu Credito en Pesos!
  p Solo sigue los pasos que se te indican a continuación.
div class="panel panel-default"
  div class="panel-heading"
    h3 class="panel-title" Llena los siguientes datos
  div class="panel-body"
    p FORM

app/views/pages/vsm.html.slim
.jumbotron
  h1 Calcula tu Credito en VSM!
  p Solo sigue los pasos que se te indican a continuación.
.panel.panel-default
  .panel-heading
    h3 class="panel-title" Llena los siguientes datos
  .panel-body
    = form_tag calcular_vsm_pages_path, class: "form-horizontal"
      .form-group
        = label_tag :vsm_home_price, "Prestamo Inicial Infonavit", class: "col-sm-3"
        .input-group.col-sm-2
          span class="input-group-addon" $
          = text_field "vsm", "home_price", class: "form-control", placeholder: "0.00"
      .form-group
        = label_tag :vsm_salary, "Sueldo Mensual", class: "col-sm-3"
        .input-group.col-sm-2
          span class="input-group-addon" $
          = text_field "vsm", "salary", class: "form-control", placeholder: "0.00"
      .form-group
        = label_tag :vsm_interest_percentage, "Porcentaje de Interés", class: "col-sm-3"
        .input-group.col-sm-1
          = text_field "vsm", "interest_percentage", class: "form-control", placeholder: "12"
          span class="input-group-addon" %
      .form-group
        = label_tag :vsm_employer_contribution, "Aportación Patronal", class: "col-sm-3"
        .input-group.col-sm-3
          span class="input-group-addon" $
          = text_field "vsm", "employer_contribution", class: "form-control", placeholder: "0.00"
          span class="input-group-addon" (Mensual)
      = submit_tag "Enviar", class: "btn btn-default"